version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: jwks-rsa
    versions:
    - 1.12.2
    - 1.12.3
    - 2.0.0
    - 2.0.1
    - 2.0.2
  - dependency-name: slugify
    versions:
    - 1.4.6
    - 1.4.7
  - dependency-name: react-toastify
    versions:
    - 7.0.2
    - 7.0.3
  - dependency-name: async-lock
    versions:
    - 1.2.8
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
